In [2]:
#classification problem by creating a new binary variable affair (did the woman have at least one affair?) and trying to predict the classification for each
#woman.
import pandas as pd
import statsmodels.api as sm
import matplotlib.pyplot as plt
import numpy as np
from patsy import dmatrices
from sklearn.linear_model import LogisticRegression
from sklearn.cross_validation import train_test_split
from sklearn import metrics
from sklearn.cross_validation import cross_val_score
dta = sm.datasets.fair.load_pandas().data
# add "affair" column: 1 represents having affairs, 0 represents not
dta['affair'] = (dta.affairs > 0).astype(int)
y, X = dmatrices('affair ~ rate_marriage + age + yrs_married + children + \
religious + educ + C(occupation) + C(occupation_husb)',
dta, return_type="dataframe")

X = X.rename(columns = {'C(occupation)[T.2.0]':'occ_2',
'C(occupation)[T.3.0]':'occ_3','C(occupation)[T.4.0]':'occ_4',
'C(occupation)[T.5.0]':'occ_5',
'C(occupation)[T.6.0]':'occ_6',
'C(occupation_husb)[T.2.0]':'occ_husb_2',
'C(occupation_husb)[T.3.0]':'occ_husb_3',
'C(occupation_husb)[T.4.0]':'occ_husb_4',
'C(occupation_husb)[T.5.0]':'occ_husb_5',
'C(occupation_husb)[T.6.0]':'occ_husb_6'})
y = np.ravel(y)
# instantiate a logistic regression model, and fit with X and y
model = LogisticRegression()
model = model.fit(X, y)

# check the accuracy on the training set
model.score(X, y)

0.72588752748978946

In [27]:
#predict for each woman
iparray=X.values
for i in range(len(iparray)):
        print(model.predict_proba([iparray[i]]))


[[ 0.66072218  0.33927782]]
[[ 0.25673185  0.74326815]]
[[ 0.61632433  0.38367567]]
[[ 0.55114683  0.44885317]]
[[ 0.68992388  0.31007612]]
[[ 0.61885648  0.38114352]]
[[ 0.46690847  0.53309153]]
[[ 0.59434524  0.40565476]]
[[ 0.51199589  0.48800411]]
[[ 0.42386578  0.57613422]]
[[ 0.26040123  0.73959877]]
[[ 0.86005934  0.13994066]]
[[ 0.32992549  0.67007451]]
[[ 0.81391031  0.18608969]]
[[ 0.59142561  0.40857439]]
[[ 0.73153621  0.26846379]]
[[ 0.59756809  0.40243191]]
[[ 0.09621267  0.90378733]]
[[ 0.20843176  0.79156824]]
[[ 0.73842816  0.26157184]]
[[ 0.82957622  0.17042378]]
[[ 0.37074477  0.62925523]]
[[ 0.29409519  0.70590481]]
[[ 0.44097407  0.55902593]]
[[ 0.61129998  0.38870002]]
[[ 0.93385725  0.06614275]]
[[ 0.41440066  0.58559934]]
[[ 0.84703594  0.15296406]]
[[ 0.22639428  0.77360572]]
[[ 0.42017465  0.57982535]]
[[ 0.31391625  0.68608375]]
[[ 0.34900888  0.65099112]]
[[ 0.46613466  0.53386534]]
[[ 0.7215855  0.2784145]]
[[ 0.85601897  0.14398103]]
[[ 0.35125714  0.64874

[[ 0.60196805  0.39803195]]
[[ 0.89669767  0.10330233]]
[[ 0.45252857  0.54747143]]
[[ 0.60097768  0.39902232]]
[[ 0.88754666  0.11245334]]
[[ 0.56212704  0.43787296]]
[[ 0.4754174  0.5245826]]
[[ 0.52053249  0.47946751]]
[[ 0.54575695  0.45424305]]
[[ 0.4410764  0.5589236]]
[[ 0.67455115  0.32544885]]
[[ 0.80491447  0.19508553]]
[[ 0.3862599  0.6137401]]
[[ 0.34465234  0.65534766]]
[[ 0.62442428  0.37557572]]
[[ 0.4403774  0.5596226]]
[[ 0.41053088  0.58946912]]
[[ 0.74599397  0.25400603]]
[[ 0.36122284  0.63877716]]
[[ 0.23022152  0.76977848]]
[[ 0.77458482  0.22541518]]
[[ 0.76679407  0.23320593]]
[[ 0.7813484  0.2186516]]
[[ 0.67471836  0.32528164]]
[[ 0.66655778  0.33344222]]
[[ 0.92659599  0.07340401]]
[[ 0.77231231  0.22768769]]
[[ 0.59322247  0.40677753]]
[[ 0.66352162  0.33647838]]
[[ 0.79432849  0.20567151]]
[[ 0.94030718  0.05969282]]
[[ 0.37210189  0.62789811]]
[[ 0.63396031  0.36603969]]
[[ 0.59494473  0.40505527]]
[[ 0.54219696  0.45780304]]
[[ 0.77979951  0.22020049]]
[[

[[ 0.4580904  0.5419096]]
[[ 0.52463155  0.47536845]]
[[ 0.38140881  0.61859119]]
[[ 0.70418349  0.29581651]]
[[ 0.69294409  0.30705591]]
[[ 0.7083818  0.2916182]]
[[ 0.52311116  0.47688884]]
[[ 0.62263557  0.37736443]]
[[ 0.79591265  0.20408735]]
[[ 0.29279908  0.70720092]]
[[ 0.62263557  0.37736443]]
[[ 0.64286976  0.35713024]]
[[ 0.76309571  0.23690429]]
[[ 0.51680854  0.48319146]]
[[ 0.53188612  0.46811388]]
[[ 0.58404142  0.41595858]]
[[ 0.87585632  0.12414368]]
[[ 0.49248211  0.50751789]]
[[ 0.29291403  0.70708597]]
[[ 0.583912  0.416088]]
[[ 0.60213107  0.39786893]]
[[ 0.53517824  0.46482176]]
[[ 0.70671976  0.29328024]]
[[ 0.62938549  0.37061451]]
[[ 0.75514837  0.24485163]]
[[ 0.56918178  0.43081822]]
[[ 0.856467  0.143533]]
[[ 0.58848416  0.41151584]]
[[ 0.82103983  0.17896017]]
[[ 0.34084087  0.65915913]]
[[ 0.78760685  0.21239315]]
[[ 0.60434317  0.39565683]]
[[ 0.5092833  0.4907167]]
[[ 0.75081072  0.24918928]]
[[ 0.38945589  0.61054411]]
[[ 0.23454815  0.76545185]]
[[ 0.8

[[ 0.59216564  0.40783436]]
[[ 0.13004124  0.86995876]]
[[ 0.21630134  0.78369866]]
[[ 0.64828113  0.35171887]]
[[ 0.83495772  0.16504228]]
[[ 0.51649369  0.48350631]]
[[ 0.68419217  0.31580783]]
[[ 0.72158741  0.27841259]]
[[ 0.42416752  0.57583248]]
[[ 0.65268407  0.34731593]]
[[ 0.74277461  0.25722539]]
[[ 0.60598127  0.39401873]]
[[ 0.44550889  0.55449111]]
[[ 0.63760853  0.36239147]]
[[ 0.86408273  0.13591727]]
[[ 0.77231231  0.22768769]]
[[ 0.48389517  0.51610483]]
[[ 0.51840819  0.48159181]]
[[ 0.23248619  0.76751381]]
[[ 0.24327448  0.75672552]]
[[ 0.1903347  0.8096653]]
[[ 0.53223682  0.46776318]]
[[ 0.54427711  0.45572289]]
[[ 0.17578857  0.82421143]]
[[ 0.54975691  0.45024309]]
[[ 0.8902968  0.1097032]]
[[ 0.21731008  0.78268992]]
[[ 0.30771735  0.69228265]]
[[ 0.57969196  0.42030804]]
[[ 0.63356001  0.36643999]]
[[ 0.86239718  0.13760282]]
[[ 0.64441364  0.35558636]]
[[ 0.32953358  0.67046642]]
[[ 0.37710664  0.62289336]]
[[ 0.13117914  0.86882086]]
[[ 0.11962475  0.8803752

[[ 0.57084033  0.42915967]]
[[ 0.23101477  0.76898523]]
[[ 0.37967979  0.62032021]]
[[ 0.16660512  0.83339488]]
[[ 0.44693039  0.55306961]]
[[ 0.73330974  0.26669026]]
[[ 0.66237645  0.33762355]]
[[ 0.76488086  0.23511914]]
[[ 0.3392329  0.6607671]]
[[ 0.58507021  0.41492979]]
[[ 0.5257902  0.4742098]]
[[ 0.28584152  0.71415848]]
[[ 0.86807177  0.13192823]]
[[ 0.63241364  0.36758636]]
[[ 0.87913697  0.12086303]]
[[ 0.67385296  0.32614704]]
[[ 0.85157815  0.14842185]]
[[ 0.7606883  0.2393117]]
[[ 0.44479041  0.55520959]]
[[ 0.55364395  0.44635605]]
[[ 0.69436435  0.30563565]]
[[ 0.48011554  0.51988446]]
[[ 0.79351405  0.20648595]]
[[ 0.78997129  0.21002871]]
[[ 0.73765716  0.26234284]]
[[ 0.38282431  0.61717569]]
[[ 0.68992388  0.31007612]]
[[ 0.41495596  0.58504404]]
[[ 0.16884477  0.83115523]]
[[ 0.4806956  0.5193044]]
[[ 0.69706468  0.30293532]]
[[ 0.75572896  0.24427104]]
[[ 0.56409145  0.43590855]]
[[ 0.56691791  0.43308209]]
[[ 0.45323848  0.54676152]]
[[ 0.75171916  0.24828084]]


[[ 0.89461316  0.10538684]]
[[ 0.29446506  0.70553494]]
[[ 0.77725934  0.22274066]]
[[ 0.88269094  0.11730906]]
[[ 0.7455594  0.2544406]]
[[ 0.64762777  0.35237223]]
[[ 0.90263866  0.09736134]]
[[ 0.61416992  0.38583008]]
[[ 0.9302793  0.0697207]]
[[ 0.62859667  0.37140333]]
[[ 0.42160612  0.57839388]]
[[ 0.69007285  0.30992715]]
[[ 0.58769715  0.41230285]]
[[ 0.61661403  0.38338597]]
[[ 0.76988289  0.23011711]]
[[ 0.76890097  0.23109903]]
[[ 0.85337821  0.14662179]]
[[ 0.81073576  0.18926424]]
[[ 0.86775571  0.13224429]]
[[ 0.74049827  0.25950173]]
[[ 0.65056052  0.34943948]]
[[ 0.86773053  0.13226947]]
[[ 0.52656689  0.47343311]]
[[ 0.86676639  0.13323361]]
[[ 0.73386968  0.26613032]]
[[ 0.68747358  0.31252642]]
[[ 0.89509241  0.10490759]]
[[ 0.73023053  0.26976947]]
[[ 0.60097768  0.39902232]]
[[ 0.5308378  0.4691622]]
[[ 0.87145293  0.12854707]]
[[ 0.71732787  0.28267213]]
[[ 0.796933  0.203067]]
[[ 0.85298044  0.14701956]]
[[ 0.82529405  0.17470595]]
[[ 0.08727813  0.91272187]]
[[

[[ 0.83786191  0.16213809]]
[[ 0.69545319  0.30454681]]
[[ 0.54376498  0.45623502]]
[[ 0.76230249  0.23769751]]
[[ 0.53543801  0.46456199]]
[[ 0.76921274  0.23078726]]
[[ 0.74490839  0.25509161]]
[[ 0.28011085  0.71988915]]
[[ 0.90408398  0.09591602]]
[[ 0.89167516  0.10832484]]
[[ 0.7988012  0.2011988]]
[[ 0.71843202  0.28156798]]
[[ 0.76921274  0.23078726]]
[[ 0.90260671  0.09739329]]
[[ 0.61485766  0.38514234]]
[[ 0.87537007  0.12462993]]
[[ 0.87376084  0.12623916]]
[[ 0.80698897  0.19301103]]
[[ 0.5280056  0.4719944]]
[[ 0.77521804  0.22478196]]
[[ 0.65898252  0.34101748]]
[[ 0.73414253  0.26585747]]
[[ 0.69205825  0.30794175]]
[[ 0.86137873  0.13862127]]
[[ 0.79306048  0.20693952]]
[[ 0.80244553  0.19755447]]
[[ 0.82893841  0.17106159]]
[[ 0.4653993  0.5346007]]
[[ 0.8533443  0.1466557]]
[[ 0.6296133  0.3703867]]
[[ 0.69878072  0.30121928]]
[[ 0.88198663  0.11801337]]
[[ 0.51856459  0.48143541]]
[[ 0.75887121  0.24112879]]
[[ 0.64489621  0.35510379]]
[[ 0.70255617  0.29744383]]
[[

[[ 0.47306307  0.52693693]]
[[ 0.69822633  0.30177367]]
[[ 0.86212917  0.13787083]]
[[ 0.81608028  0.18391972]]
[[ 0.52731682  0.47268318]]
[[ 0.88878012  0.11121988]]
[[ 0.75799991  0.24200009]]
[[ 0.90658868  0.09341132]]
[[ 0.62929568  0.37070432]]
[[ 0.69108904  0.30891096]]
[[ 0.87938006  0.12061994]]
[[ 0.82581673  0.17418327]]
[[ 0.62121286  0.37878714]]
[[ 0.53842344  0.46157656]]
[[ 0.68480019  0.31519981]]
[[ 0.81306144  0.18693856]]
[[ 0.76555687  0.23444313]]
[[ 0.67011864  0.32988136]]
[[ 0.42990422  0.57009578]]
[[ 0.89967608  0.10032392]]
[[ 0.85839372  0.14160628]]
[[ 0.29577423  0.70422577]]
[[ 0.82279449  0.17720551]]
[[ 0.88918  0.11082]]
[[ 0.54923885  0.45076115]]
[[ 0.81177221  0.18822779]]
[[ 0.89778159  0.10221841]]
[[ 0.51135907  0.48864093]]
[[ 0.81947127  0.18052873]]
[[ 0.79154629  0.20845371]]
[[ 0.85772385  0.14227615]]
[[ 0.94418825  0.05581175]]
[[ 0.67799944  0.32200056]]
[[ 0.69003295  0.30996705]]
[[ 0.42613057  0.57386943]]
[[ 0.85606427  0.14393573]

[[ 0.23003436  0.76996564]]
[[ 0.88996553  0.11003447]]
[[ 0.59350698  0.40649302]]
[[ 0.78118336  0.21881664]]
[[ 0.74772393  0.25227607]]
[[ 0.81901228  0.18098772]]
[[ 0.75750034  0.24249966]]
[[ 0.6000072  0.3999928]]
[[ 0.60267699  0.39732301]]
[[ 0.30969812  0.69030188]]
[[ 0.68936263  0.31063737]]
[[ 0.89704212  0.10295788]]
[[ 0.86225094  0.13774906]]
[[ 0.8492153  0.1507847]]
[[ 0.86579519  0.13420481]]
[[ 0.74901974  0.25098026]]
[[ 0.59634765  0.40365235]]
[[ 0.70290626  0.29709374]]
[[ 0.668432  0.331568]]
[[ 0.7083818  0.2916182]]
[[ 0.67942791  0.32057209]]
[[ 0.78216192  0.21783808]]
[[ 0.92127065  0.07872935]]
[[ 0.72713767  0.27286233]]
[[ 0.81417748  0.18582252]]
[[ 0.75202759  0.24797241]]
[[ 0.89707286  0.10292714]]
[[ 0.90808751  0.09191249]]
[[ 0.87010663  0.12989337]]
[[ 0.9052547  0.0947453]]
[[ 0.84317311  0.15682689]]
[[ 0.76859715  0.23140285]]
[[ 0.86524175  0.13475825]]
[[ 0.76979353  0.23020647]]
[[ 0.83504002  0.16495998]]
[[ 0.45662652  0.54337348]]
[[ 0

[[ 0.90408398  0.09591602]]
[[ 0.89234913  0.10765087]]
[[ 0.46117797  0.53882203]]
[[ 0.39422606  0.60577394]]
[[ 0.44375254  0.55624746]]
[[ 0.55352796  0.44647204]]
[[ 0.71795619  0.28204381]]
[[ 0.83147431  0.16852569]]
[[ 0.77438378  0.22561622]]
[[ 0.74689391  0.25310609]]
[[ 0.43488133  0.56511867]]
[[ 0.47573961  0.52426039]]
[[ 0.7232428  0.2767572]]
[[ 0.91583317  0.08416683]]
[[ 0.71040191  0.28959809]]
[[ 0.86661997  0.13338003]]
[[ 0.70301795  0.29698205]]
[[ 0.45035019  0.54964981]]
[[ 0.75460697  0.24539303]]
[[ 0.7705627  0.2294373]]
[[ 0.83841018  0.16158982]]
[[ 0.88926423  0.11073577]]
[[ 0.85509211  0.14490789]]
[[ 0.64363187  0.35636813]]
[[ 0.89193843  0.10806157]]
[[ 0.91770588  0.08229412]]
[[ 0.7599258  0.2400742]]
[[ 0.8182965  0.1817035]]
[[ 0.72774183  0.27225817]]
[[ 0.71093961  0.28906039]]
[[ 0.64471174  0.35528826]]
[[ 0.57054629  0.42945371]]
[[ 0.87488674  0.12511326]]
[[ 0.70825809  0.29174191]]
[[ 0.66045073  0.33954927]]
[[ 0.81126966  0.18873034]]


[[ 0.80909165  0.19090835]]
[[ 0.51501531  0.48498469]]
[[ 0.62649454  0.37350546]]
[[ 0.85723304  0.14276696]]
[[ 0.84045756  0.15954244]]
[[ 0.58191669  0.41808331]]
[[ 0.89323922  0.10676078]]
[[ 0.81222404  0.18777596]]
[[ 0.75122362  0.24877638]]
[[ 0.68478438  0.31521562]]
[[ 0.68539112  0.31460888]]
[[ 0.82424365  0.17575635]]
[[ 0.5519713  0.4480287]]
[[ 0.85075718  0.14924282]]
[[ 0.86949008  0.13050992]]
[[ 0.7496163  0.2503837]]
[[ 0.83614347  0.16385653]]
[[ 0.53235832  0.46764168]]
[[ 0.9197387  0.0802613]]
[[ 0.76475346  0.23524654]]
[[ 0.82972257  0.17027743]]
[[ 0.60832677  0.39167323]]
[[ 0.84013506  0.15986494]]
[[ 0.69078926  0.30921074]]
[[ 0.89083629  0.10916371]]
[[ 0.81216618  0.18783382]]
[[ 0.61977609  0.38022391]]
[[ 0.54945904  0.45054096]]
[[ 0.48548182  0.51451818]]
[[ 0.82206558  0.17793442]]
[[ 0.92716606  0.07283394]]
[[ 0.62442428  0.37557572]]
[[ 0.5506235  0.4493765]]
[[ 0.80817123  0.19182877]]
[[ 0.70171238  0.29828762]]
[[ 0.64742448  0.35257552]]
